# This workflow will install Python dependencies, run tests and linters
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  workflow_call:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
          enable-cache: true
      - name: Install project dependencies
        run: uv sync --all-groups --all-extras
      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.local/share/uv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
          enable-cache: true
      - name: Restore cached venv
        uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.local/share/uv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
      - name: Lint with pre-commit
        run: ./.venv/bin/pre-commit run --all-files
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cached venv
        uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.local/share/uv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
      - name: Run tests with pytest
        run: ./.venv/bin/pytest
